### ISSUE TITLE
Keyboard covering up my input field

### ISSUE THREAD

**Issue by jrmcdona** [ionic-team/ionic-plugin-keyboard#275]
Hello,
When I have this.keyboard.disableScroll(true); then the Keyboard covers up my input field and I cannot get the keyboard to go away.   

If I do no use the above setting, then I can see my input box but everything else is pushed up and out of site.  This also behaves really poor when the keyboard slides downward.

My forums thread is here:
https://forum.ionicframework.com/t/keyboard-pushes-elements-out-of-top-of-view/51212/16

What settings should I be using here or what might I be doing wrong?

Cordova CLI: 6.4.0
Ionic Framework Version: 3.0.1
Ionic CLI Version: 2.1.14
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 1.3.0
ios-deploy version: 1.9.1
ios-sim version: 5.0.12
OS: macOS Sierra
Node Version: v7.4.0
Xcode version: Xcode 8.3.2 Build version 8E2002

![screen shot 2017-05-15 at 4 58 59 pm](https://cloud.githubusercontent.com/assets/4327773/26081312/d713569e-398f-11e7-89bd-867399bab122.png)

![screen shot 2017-05-15 at 5 02 43 pm](https://cloud.githubusercontent.com/assets/4327773/26081426/5d46bdfa-3990-11e7-98a6-3e7ee829c037.png)

**Comment by jrmcdona** [comment]
I also tried this.  Didn't work.

https://gist.github.com/EvanWillms/8773f8cfa12f469fabf0bdd7a75723e7

**Comment by tobiasmuecksch** [comment]
There is kind of a solution 
https://github.com/ionic-team/ionic/issues/5432

**Comment by jrmcdona** [comment]
@tobiasmuecksch the WKWebView version did pretty good for me.  However,  we ended up purchasing the keyboard plugin from Eddie.   It used to be linked from the official Ionic site. 

https://github.com/EddyVerbruggen/cordova-plugin-native-keyboard

It costs money but worked well and Ionic was/is still working on their chat solution and I needed to move forward.
