### ISSUE TITLE
Keyboard does not show on android 7 with --prod flag

### ISSUE THREAD

**Issue by hussembadri** [ionic-team/ionic-plugin-keyboard#307]
It is also mentioned [here](https://forum.ionicframework.com/t/keyboard-doesnt-show-when-building-with-prod-on-android-nougat/111721).

**Comment by pablogarciamiranda** [comment]
[https://github.com/ionic-team/ionic/issues/13718](https://github.com/ionic-team/ionic/issues/13718) Solved there
